version: 2

models:
  - name: bronze_listings  
    description: "Les données brutes chargées en mode incremental avec date de creation > max date de creation de  bronze_listings et gestion des doublons."
    
  - name: bronze_hosts
    description: "Les données brutes chargées en mode incremental avec date de creation > max date de creation de  bronze_hosts et gestion des doublons."
    
  - name: bronze_bookings
    description: "Les données brutes chargées en mode incremental avec date de creation > max date de creation de  bronze_bookings et gestion des doublons."

  - name: silver_listings
    description: "Les données nettoyées et transformées et enrichies en mode incremental avec date de creation > max date de creation de  silver_listings"

  - name: silver_hosts
    description: "Les données nettoyées et transformées et enrichies en mode incremental avec date de creation > max date de creation de  silver_hosts"

  - name: silver_bookings
    description: "Les données nettoyées et transformées et enrichies en mode incremental avec unique_key = booking_id"

  - name: obt
    description: "OBT (One Big Table) est : Une table unique et dénormalisée qui contient toutes les dimensions et métriques nécessaires pour l’analyse. "

  - name: dim_hosts
    description: "Chaque ligne représente une version d’un hôte valide sur une période donnée. (snapshot SCD-2)"

  - name: dim_listings
    description: "Chaque ligne représente une version d’un listing valide sur une période donnée. (snapshot SCD-2)"

  - name: dim_bookings
    description: "Chaque ligne représente une version d’une réservation valide sur une période donnée. (snapshot SCD-2)"

