CREATE OR REPLACE DATABASE AIRBNB;
CREATE OR REPLACE SCHEMA STAGING;
CREATE OR REPLACE SCHEMA BRONZE;

-- Drop schema bublic
drop schema AIRBNB.public;
  
-- Create Api integration + secret then create a workspace "from GIT REPOSITORY"
CREATE SECRET git_secret
  TYPE = PASSWORD
  USERNAME = 'my_user'
  PASSWORD = 'my_token';

CREATE OR REPLACE API INTEGRATION git_my_proj
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/useur/')
  ALLOWED_AUTHENTICATION_SECRETS = (git_secret)
  ENABLED = TRUE;


-- DDL For My Tables
--STAGING
CREATE OR REPLACE TRANSIENT TABLE AIRBNB.STAGING.HOSTS (
    host_id NUMBER,
    host_name STRING,
    host_since DATE,
    is_superhost BOOLEAN,
    response_rate NUMBER,
    created_at TIMESTAMP,
    PRIMARY KEY (host_id)
);

CREATE OR REPLACE TRANSIENT TABLE AIRBNB.STAGING.LISTINGS (
    listing_id NUMBER,
    host_id NUMBER,
    property_type STRING,
    room_type STRING,
    city STRING,
    country STRING,
    accommodates NUMBER,
    bedrooms NUMBER,
    bathrooms NUMBER,
    price_per_night NUMBER,
    created_at TIMESTAMP,
    PRIMARY KEY (listing_id)
);

CREATE OR REPLACE TRANSIENT TABLE AIRBNB.STAGING.BOOKINGS (
    booking_id STRING,
    listing_id NUMBER,
    booking_date TIMESTAMP,
    nights_booked NUMBER,
    booking_amount NUMBER,
    cleaning_fee NUMBER,
    service_fee NUMBER,
    booking_status STRING,
    created_at TIMESTAMP,
    PRIMARY KEY (booking_id)
);

-- BRONZE
create or replace TRANSIENT TABLE AIRBNB.BRONZE.BRONZE_BOOKINGS (
	BOOKING_ID VARCHAR(16777216),
	LISTING_ID NUMBER(38,0),
	BOOKING_DATE TIMESTAMP_NTZ(9),
	NIGHTS_BOOKED NUMBER(38,0),
	BOOKING_AMOUNT NUMBER(38,0),
	CLEANING_FEE NUMBER(38,0),
	SERVICE_FEE NUMBER(38,0),
	BOOKING_STATUS VARCHAR(16777216),
	CREATED_AT TIMESTAMP_NTZ(9),
	ETL_LOADED_AT VARCHAR DEFAULT TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYY-MM-DD"T"HH24:MI:SS'),
    PRIMARY KEY (booking_id)
);

create or replace TRANSIENT TABLE AIRBNB.BRONZE.BRONZE_HOSTS (
	HOST_ID NUMBER(38,0),
	HOST_NAME VARCHAR(16777216),
	HOST_SINCE DATE,
	IS_SUPERHOST BOOLEAN,
	RESPONSE_RATE NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	ETL_LOADED_AT VARCHAR DEFAULT TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYY-MM-DD"T"HH24:MI:SS'),
    PRIMARY KEY (host_id)
);

create or replace TRANSIENT TABLE AIRBNB.BRONZE.BRONZE_LISTINGS (
	LISTING_ID NUMBER(38,0),
	HOST_ID NUMBER(38,0),
	PROPERTY_TYPE VARCHAR(16777216),
	ROOM_TYPE VARCHAR(16777216),
	CITY VARCHAR(16777216),
	COUNTRY VARCHAR(16777216),
	ACCOMMODATES NUMBER(38,0),
	BEDROOMS NUMBER(38,0),
	BATHROOMS NUMBER(38,0),
	PRICE_PER_NIGHT NUMBER(38,0),
	CREATED_AT TIMESTAMP_NTZ(9),
	ETL_LOADED_AT VARCHAR DEFAULT TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYY-MM-DD"T"HH24:MI:SS'),
    PRIMARY KEY (listing_id)
);