
name: 'airbnb_proj_dbt_snowflake'
version: '1.0.0'

profile: 'airbnb_proj_dbt_snowflake'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  airbnb_proj_dbt_snowflake:
    bronze:
      +schema: bronze
      +materialized: table
    
    silver:
      +schema: silver
      +materialized: table 
    
    gold:
      +schema: gold
      +materialized: table 
      +transient: false

      ephemeral: 
        +materialized: ephemeral
