sources:
    - name: staging
      database: AIRBNB
      schema: STAGING
      tables:
        - name: listings
          description: "Listings table: elle contient les informations sur les biens mis en location sur Airbnb"
          
          columns:
            - name: listing_id
              description: "Listing id: identifiant unique du listing"
              tests:
                - not_null
            - name: host_id
              description: "Host id: identifiant unique du host"
              tests:
                - not_null
                - relationships:
                    to: source('staging', 'hosts')
                    field: host_id
          

        - name: hosts
          description: "Hosts table: elle contient les informations sur les personnes qui publient les logements."
        
          columns:
            - name: host_id
              description: "Host id: identifiant unique du host"
              tests:
                - not_null
        

        - name: bookings
          description: "Bookings table: la table transactionnelle. Elle contient les données sur les séjours réellement réservés"

          columns:
            - name: booking_id
              description: "Booking id: identifiant unique du booking"
              tests:
                - not_null

            - name: listing_id
              description: "Listing id: identifiant unique du listing"
              tests:
                - not_null
                - relationships:
                    to: source('staging', 'listings')
                    field: listing_id
          
            - name: booking_status
              description: "Booking status: statut de la réservation"
              tests:
                - accepted_values:
                    values: ["cancelled", "confirmed"]

            - name: booking_date
              description: "Booking date: date de la réservation"
              tests:
                - not_null
           
            - name: nights_booked
              description: "Nights booked: nombre de nuits réservées"
              tests:
                - not_null
                - dbt_utils.expression_is_true:
                    arguments: 
                        expression: ">= 1" 
                        



