name: dbt CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt
        run: |
          pip install dbt-snowflake

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          Airbnb_proj_Stach_AWS_Snowflake_DBT:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
                user: "{{ env_var('SNOWFLAKE_USER') }}"
                password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
                role: ACCOUNTADMIN
                warehouse: COMPUTE_WH
                database: AIRBNB
                schema: PIPELINE
                threads: 4
          EOF

      - name: Install project dependencies
        working-directory: Airbnb_proj_Stach_AWS_Snowflake_DBT/Airbnb_proj_Stach_AWS_Snowflake_DBT
        run: dbt deps
        
      - name: Run dbt debug
        working-directory: Airbnb_proj_Stach_AWS_Snowflake_DBT/Airbnb_proj_Stach_AWS_Snowflake_DBT
        run: dbt debug

      - name: Run dbt tests
        working-directory: Airbnb_proj_Stach_AWS_Snowflake_DBT/Airbnb_proj_Stach_AWS_Snowflake_DBT
        run: dbt test

      - name: Clean target directory
        run: rm -rf Airbnb_proj_Stach_AWS_Snowflake_DBT/Airbnb_proj_Stach_AWS_Snowflake_DBT/target
        
      - name: Generate dbt documentation
        working-directory: Airbnb_proj_Stach_AWS_Snowflake_DBT/Airbnb_proj_Stach_AWS_Snowflake_DBT
        run: dbt docs generate

      #- name: Fix dbt docs for GitHub Pages
      #  run: |
      #   sed -i 's|href="/|href="./|g' ./Airbnb_proj_Stach_AWS_Snowflake_DBT/Airbnb_proj_Stach_AWS_Snowflake_DBT/target/index.html
 
      - name: Publish dbt docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./Airbnb_proj_Stach_AWS_Snowflake_DBT/Airbnb_proj_Stach_AWS_Snowflake_DBT/target
          publish_branch: gh-pages
          force_orphan: true
          keep_files: false
          allow_empty_commit: false
          enable_jekyll: false
          disable_nojekyll: false
          exclude_assets: .github
